sudo: false
language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - composer config --global github-oauth.github.com $TRAVIS_GITHUB_TOKEN
  - composer remove --dev --no-update phpunit/phpunit
  - composer require satooshi/php-coveralls --no-update

install:
  - composer install --no-dev

after_script:
  - php vendor/bin/coveralls
