sudo: false
language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - composer config --global github-oauth.github.com $TRAVIS_GITHUB_TOKEN
  - composer remove --dev --no-update phpunit/phpunit
  - composer require php-coveralls/php-coveralls --no-update
  - composer require codacy/coverage --no-update

install:
  - composer update --no-dev

script:
  - phpunit

after_script:
  - php vendor/bin/php-coveralls
  - php vendor/bin/codacycoverage clover report/coverage-clover/clover.xml
